version: "3.8"

services:
  database:
    image: postgres:16
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: backend_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: node_app
    restart: always
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: backend_db
      JWT_SECRET: 61191133-6b0c-4725-b18d-d8f116cbdf4b
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: >
      sh -c "npm install && npm run build && npm run typeorm migration:run -- -d dist/config/typeorm.config.js && npm run start:dev"

volumes:
  pg_data:
